[package]
name = "wallet_classifier"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.99"
ethers = "2.0.14"
reqwest = "0.12.23"
serde_json = "1.0.143"
tokio = { version = "1.47.1", features = ["full"] }
